name: slide_up_flutter
description: Slide up widget in your app
version: 0.0.1
author: Ricardo Romero Benitez
homepage: https://github.com/RicardoRB/slide_up_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
